### PR TITLE
Save Plot, scale plot, subset data range

### PR DESCRIPTION
**Pull request by a1729nikora**
These changes implement subsetting by data range, saving data and trend plots, and scaling the data and trend plots by linking the plot height to its width, which is automatically set (ggplot doesn't do auto height correctly).

The data and trend plot has been renamed "DataAndTrendPlot" from "distPlot" in ui.R.

### CODE REVIEW

**Comment by arhik** [comment]
Hello alen ... does this code break the flow in any of the four tabs.

**Comment by arhik** [comment]
I observed that when different models were selected in the third tab and we navigate back to second tab there will be an error in the plot area.

**Comment by arhik** [comment]
This is where we need to track the models too....

**Comment by arhik** [comment]
I fixed it in the last commit. But git says its up-to-date with the base branch. I dont really know why. But i trusted it the same way you do last time and i spent a lot of debugging time  to make it functional again...

**Comment by arhik** [comment]
Let me know if you still struggle to understand what we mean.... If you feel there is a way around other than keeping track of models, we are open to look into it. Keep posting us with your updates. 

Thanking you
karthik

**Comment by a1729nikora** [comment]
HI, Karthik,

Thanks for the note – I haven’t gotten to that part on the third tab yet.

Regards,
Allen N.

# 

   Allen P. Nikora, Ph.D.
   Program Element Manager,
        Assurance Technology Program Office Software Element

   Jet Propulsion Laboratory
   California Institute of Technology
   4800 Oak Grove Drive
   Pasadena, CA  91109-8099
   Mail Stop 125-233

   vox: 818.393.1104
   fax: 818.393.1362
   email: Allen.P.Nikora@jpl.nasa.gov

#

**Pull request merged**
