### PR TITLE
Reading input files

### PR DESCRIPTION
**Pull request by a1729nikora**
Hi, everybody.  I've made changes in my fork that replace the hard-coded list of data sheet names for Excel files with a dynamically populated list of data sheet names once an Excel file has been opened.  I still need to do basic error checking once a file has been opened, but I'd rather have multiple small changes to merge in rather than a big one.

### CODE REVIEW

**Comment by arhik** [comment]
Hello Allen,

```
     Auto popup of excel sheet names is done already. Sorry to make you work on that again. We have shown you its working in the past two meetings, may be we didn't made that clear. It is tough for us to use your code now because there were many changes here. I will try to merge other commits made by you. Separate file for Error messages is good idea for organizing code by the way. Thank you. Please let us know if there is anything else. The code in the repository needs a heavy clean up and refactoring from my side  and I will try to update the changes from now on as soon as possible.   
```

Thanking you.
karthik

**Comment by a1729nikora** [comment]
Thanks, Karthik!  It was good practice to do the auto popup of sheet names. I guess I didn’t catch that in the past couple of telecons.

I’ll make sure to keep synced with what you guys are doing – if I have any questions, I’ll let you know.

Regares,
Allen N.

# 

   Allen P. Nikora, Ph.D.
   Program Element Manager,
        Assurance Technology Program Office Software Element

   Jet Propulsion Laboratory
   California Institute of Technology
   4800 Oak Grove Drive
   Pasadena, CA  91109-8099
   Mail Stop 125-233

   vox: 818.393.1104
   fax: 818.393.1362
   email: Allen.P.Nikora@jpl.nasa.gov

#

**Comment by a1729nikora** [comment]
Hi, Karthik,

  I hope you get this request.  The changes I'm interested in merging are the ones under the heading "a1729nikora added some commits 17 days ago."  Most of what I've done is on the first panel, and it doesn't seem to affect what you guys have been doing there.

  Please let me know if you have questions about any of these changes.

Regards,
Allen N.

**Comment by arhik** [comment]
Hi Allen, 
Please pull the recent copy again and replace the code with yours. Looks like there is a conflict now. Thats the only way to resolve it.

karthik

**Comment by a1729nikora** [comment]
Thanks, Karthik!  I’ll take care of it.

-Allen N.

# 

   Allen P. Nikora, Ph.D.
   Program Element Manager,
        Assurance Technology Program Office Software Element

   Jet Propulsion Laboratory
   California Institute of Technology
   4800 Oak Grove Drive
   Pasadena, CA  91109-8099
   Mail Stop 125-233

   vox: 818.393.1104
   fax: 818.393.1362
   email: Allen.P.Nikora@jpl.nasa.gov

#

**Comment by arhik** [comment]
Thanks..

**Comment by a1729nikora** [comment]
Thanks, Karthik!

-Allen N.

# 

   Allen P. Nikora, Ph.D.
   Program Element Manager,
        Assurance Technology Program Office Software Element

   Jet Propulsion Laboratory
   California Institute of Technology
   4800 Oak Grove Drive
   Pasadena, CA  91109-8099
   Mail Stop 125-233

   vox: 818.393.1104
   fax: 818.393.1362
   email: Allen.P.Nikora@jpl.nasa.gov

#

**Pull request merged**
